name: Build Success Setu APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: pwa-builder/pwa-action@v2
        with:
          # Aapka website URL
          pwa-url: "https://kartiksinghania14357-creator.github.io/SuccessSetuApp/"
          android-package-id: "com.success.setu"
          android-app-name: "Success Setu"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: success-setu-app
          path: ./**/*.apk
